### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [Tchoupinax/tilt-vscode-extension#1]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _Tilt_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by Tchoupinax** [comment]
Hello,

I'm a VSCodium user too :) But i did not have knowledge of open-vsx.org. It could be Interesting to upload on it.

What advantages do you see about using this platform instead of Microsoft's maketplace ?

**Comment by orblazer** [comment]
The mainly advantages to use open-vsx is for have an full open source event in marketplace.

**Comment by Tchoupinax** [comment]
Hello !

The extension has been published on open-vsx (https://open-vsx.org/extension/Tchoupinax/tilt)
Thank you for your suggest :)

Have fun !
