### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by spoenemann** [Tchoupinax/tilt-vscode-extension#6]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by Tchoupinax** [comment]
Hello @spoenemann !

Thank you for your alert. I just created my Eclipse account and it seems to be good :)

<img width="806" alt="image" src="https://user-images.githubusercontent.com/9136206/103647339-71839880-4f5b-11eb-8b61-fe65b0972fa5.png">

I will wait until January 9 and then I will close the issue.

**Comment by spoenemann** [comment]
Great! No need to wait though, all necessary steps are done.

**Comment by Tchoupinax** [comment]
Thanks 🙌

**Comment by spoenemann** [comment]
Hi @Tchoupinax! I noticed another problem that needs to be addressed so the extension can remain available on open-vsx.org: The license file is currently named `LICENCE.md`, but it should be `LICENSE.md`. Because of this, the extension is currently detected as "unlicensed", which violates the new terms set by the Eclipse Foundation.

Could you rename the file and then publish a new version of the extension?

Thank you!

**Comment by Tchoupinax** [comment]
Hey !

The version 1.0.6 is published for 3 days and should solve the issue. Please notice me if there is another issue.
https://open-vsx.org/extension/Tchoupinax/tilt

Thank you for you message :)
