### ISSUE TITLE
Double quote `""` strings?

### ISSUE THREAD

**Issue by ottaviohartman** [Tchoupinax/tilt-vscode-extension#8]
Can double-quoted strings be added to this extension? It would help as we run `black` formatter over Tiltfiles

**Comment by Tchoupinax** [comment]
Hello @omh1280 !

Thank you for your interest :)

I made the change, it is right ?

Before:
![image](https://user-images.githubusercontent.com/9136206/113850769-18feaa00-979b-11eb-96d3-8d42c915a6e3.png)

After:
![image](https://user-images.githubusercontent.com/9136206/113850674-fff5f900-979a-11eb-9bc4-b427b86a8875.png)

I will publish the fix if you approve it

**Comment by ottaviohartman** [comment]
Yes that’s perfect, thanks for the timely response!

**Comment by Tchoupinax** [comment]
You're welcome

Extension is released to solve your issue :) 
https://github.com/Tchoupinax/tilt-vscode-extension/releases/tag/v1.0.7
